### ISSUE TITLE
There is no completion popup on Common Lisp extension files, even though everything required is installed

### ISSUE THREAD

**Issue by fluteguitar** [purcell/ac-slime#12]
![image](https://cloud.githubusercontent.com/assets/10528635/21937563/74df5180-d9ea-11e6-9cb8-567e4c6411f5.png)
As from the picture, I have installed auto-complete, slime, and ac-slime. They are enable as shown in modeline.

This is my emacs init file: ~/.emacs. 

```lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold])
 '(ansi-color-names-vector ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"])
 '(custom-enabled-themes (quote (light-blue)))
 '(custom-safe-themes (quote ("28ec8ccf6190f6a73812df9bc91df54ce1d6132f18b4c8fcc85d45298569eb53" default)))
 '(fci-rule-color "#14151E")
 '(vc-annotate-background nil)
 '(vc-annotate-color-map (quote ((20 . "#d54e53") (40 . "goldenrod") (60 . "#e7c547") (80 . "DarkOliveGreen3") (100 . "#70c0b1") (120 . "DeepSkyBlue1") (140 . "#c397d8") (160 . "#d54e53") (180 . "goldenrod") (200 . "#e7c547") (220 . "DarkOliveGreen3") (240 . "#70c0b1") (260 . "DeepSkyBlue1") (280 . "#c397d8") (300 . "#d54e53") (320 . "goldenrod") (340 . "#e7c547") (360 . "DarkOliveGreen3"))))
 '(vc-annotate-very-old-color nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(setq inferior-lisp-program "sbcl")
(load (expand-file-name "~/quicklisp/slime-helper.el"))
(electric-indent-mode +1)
(require 'package)

;; If you want to use latest version
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

;; If you want to use last tagged version
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
(package-initialize)
(ac-config-default)
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)

(add-hook 'slime-mode-hook 'set-up-slime-ac)
(add-hook 'slime-repl-mode-hook 'set-up-slime-ac)
(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'slime-repl-mode))

;; Set your lisp system and, optionally, some contribs
(setq inferior-lisp-program "/opt/sbcl/bin/sbcl")
(setq slime-contribs '(slime-fancy))
```

**Comment by fluteguitar** [comment]
Another information: auto-complete on my emacs has been tested successfully on other programming languages.

**Comment by farzadbekran** [comment]
This is how i config my slime-ac these days, try it keep in mind that the
shortcuts are mapping to paredit commands, you might want to change some
things around:

(setq inferior-lisp-program "/usr/bin/sbcl")
(setq slime-contribs '(slime-fancy)) ; almost everything

(defun add-ac-slime-fuzzy ()
  (setq ac-sources '(ac-source-slime-fuzzy)))

(add-hook 'slime-repl-mode-hook 'auto-complete-mode)
(add-hook 'slime-repl-mode-hook 'paredit-mode)
(add-hook 'slime-repl-mode-hook 'add-ac-slime-fuzzy)
(add-hook 'slime-mode-hook 'add-ac-slime-fuzzy)

(defun fix-lisp-commands ()
  "Fixes my favorite Lisp shortcuts in Lisp related modes."
  (setq lisp-indent-function 'common-lisp-indent-function)
  (define-key slime-mode-map (kbd "<return>")
    'newline-and-indent)
  (define-key slime-mode-map (kbd "<C-backspace>")
    'backward-kill-sexp)
  (define-key slime-mode-map (kbd "<C-delete>")
    'kill-sexp)

  (ignore-errors
    (define-key slime-repl-mode-map (kbd "<C-backspace>")
      'backward-kill-sexp)
    (define-key slime-repl-mode-map (kbd "<C-delete>")
      'kill-sexp)
    (define-key slime-repl-mode-map "\C-c\C-s" 'slime-selector))

  (define-key emacs-lisp-mode-map (kbd "<return>")
    'newline-and-indent)
  (define-key emacs-lisp-mode-map (kbd "<C-backspace>")
    'backward-kill-sexp)
  (define-key emacs-lisp-mode-map (kbd "<C-delete>")
    'kill-sexp))

(add-hook 'slime-mode-hook 'fix-lisp-commands)
(add-hook 'slime-repl-mode-hook 'fix-lisp-commands)
(add-hook 'emacs-lisp-mode 'fix-lisp-commands)
(add-hook 'lisp-mode 'fix-lisp-commands)

**Comment by fluteguitar** [comment]
Hello, farzadbekran

Thanks for your reply. Since your .emacs file content are a pretty complicated to me (I am a newbie in Clisp and Emacs). It would take effort for me to comprehend everything in the file.

So could you elaborate more on the most viable point towards a solution which I need to focus on? Do you mean 'paredit'?

**Comment by farzadbekran** [comment]
Ok let me try to explain things a bit:

;;this sets up your lisp implementation to use
(setq inferior-lisp-program "/usr/bin/sbcl")
;;this selects the features you want enabled, 'slime-fancy' is a meta
feature that enables most of them
(setq slime-contribs '(slime-fancy)) ; almost everything

;;we define a function here that when run, sets 'ac-source-slime-fuzzy' as
the only source available to auto-complete package, ac-slime provides this
source
(defun add-ac-slime-fuzzy ()
  (setq ac-sources '(ac-source-slime-fuzzy)))

;;these are hooks, ie when a buffer that its major mode is
'slime-repl-mode' is created for the first time, all the functions you add
to its hook are called. So for example, in the first line here, we enable
auto-complete-mode when a slime-repl buffer is created.
(add-hook 'slime-repl-mode-hook 'auto-complete-mode)
(add-hook 'slime-repl-mode-hook 'paredit-mode)

;;here we make sure that in slime-repl buffers we set the source for
auto-complete to be the one ac-slime provides, using the function we
defined earlier
(add-hook 'slime-repl-mode-hook 'add-ac-slime-fuzzy)

;;same for the slime buffers
(add-hook 'slime-mode-hook 'add-ac-slime-fuzzy)

You can ignore the rest as they are only for seting up shortcuts in
different buffers. Hope this helps.

**Comment by fluteguitar** [comment]
Thanks for all the comment, I have solve the issue by switching **major mode** to ```Emacs-lisp``` instead of ```Lisp```.
