### ISSUE TITLE
Installation Does Not Work on MELPA and From File

### ISSUE THREAD

**Issue by artforlife** [purcell/ac-slime#14]
I am not able to install this using neither MELPA nor from-file installation.

The former returns "package not found" and the latter returns "Package lacks a Version or Package Version container".

**Comment by purcell** [comment]
Re. the former message, I expect your package list is out of date. Try `M-x package-refresh-contents` then try again. Re. the second, I've added a placeholder header which will allow from-file installation, but MELPA is still the preferred option.

I've personally moved from `auto-complete` to `company`, so I'm not maintaining or using this package. There's a `company` equivalent of this package in MELPA, IIRC.

**Comment by artforlife** [comment]
Thank for the recommendation. The package refresh worked. Also, the `company` seems good. What features does it have that made you switch?

**Comment by artforlife** [comment]
Also, after checking out the `company`, I still like your module better. Company is buggy for me and is hard to get working. I like the interface of `ac-slime` and `auto-complete` much better too.

**Comment by purcell** [comment]
> Also, after checking out the company, I still like your module better. Company is buggy for me and is hard to get working. I like the interface of ac-slime and auto-complete much better too.

Cool. It took a while for me to switch over. If `auto-complete` is working for you, then great! :-)
