### ISSUE TITLE
Error running timer

### ISSUE THREAD

**Issue by MartinBuchmann** [purcell/ac-slime#15]
I am getting the following error messages when I am using `ac-slime`. In others modes I do not see this issue when using auto-complete. I am using Emacs 26 but am not sure if this was happening before the upgrade. I re-installed all autocomplete packages from `melpa` without a change.

```
Error running timer ‘ac-update-greedy’: (wrong-type-argument number-or-marker-p \.\.\.) [3 times]
Error running timer ‘ac-show-menu’: (wrong-type-argument number-or-marker-p \.\.\.)
```

**Comment by purcell** [comment]
Argh, I'm not sure what the cause would be, sorry. I no longer use `auto-complete`, so I don't have a set-up with which to reproduce this. You might consider switching to https://github.com/anwyn/slime-company.

**Comment by MartinBuchmann** [comment]
Thanks for your reply, anyway. I think I found it: Somehow the `ac-comphist.dat` file was corrupted. I deleted it and everything is fine again. Please close this issue.

**Comment by purcell** [comment]
Great, glad you figured it out.
